"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const steps = [
	{ icon: "🧠", number: "01", title: "AI Generates", description: "Paste any lesson, subject, or text — our AI crafts 10 challenging quiz questions instantly." },
	{ icon: "📱", number: "02", title: "Students Join", description: "Share a unique 6-digit game code. Players join with a nickname and get ready to battle." },
	{ icon: "🏆", number: "03", title: "Battle & Win", description: "Answer fast, keep your streak, earn XP, and climb the live leaderboard to victory." }
];

const features = [
	{ icon: "⚡", title: "AI-Powered", description: "Questions generated by cutting-edge AI from any content you provide." },
	{ icon: "📡", title: "Real-Time", description: "Live leaderboard updates, instant scoring, and multiplayer competition." },
	{ icon: "🎮", title: "Gamified", description: "Lives, streaks, XP, levels, achievements — a full gaming experience." },
	{ icon: "📊", title: "Analytics", description: "Track performance, see detailed results, and measure improvement." }
];

const stats = [
	{ value: "10", label: "Questions", icon: "❓" },
	{ value: "30s", label: "Timer", icon: "⏱️" },
	{ value: "3", label: "Lives", icon: "❤️" },
	{ value: "Live", label: "Rankings", icon: "📈" }
];

export default function HomePage() {
	const [mounted, setMounted] = useState(false);

	useEffect(() => {
		setMounted(true);
	}, []);

	return (
		<div className="relative overflow-hidden">
			{/* Floating background orbs */}
			<div className="pointer-events-none absolute inset-0 overflow-hidden" aria-hidden="true">
				<div className="absolute -left-20 top-20 h-72 w-72 rounded-full bg-accent/10 blur-3xl animate-float" />
				<div className="absolute right-10 top-60 h-56 w-56 rounded-full bg-primary/10 blur-3xl animate-floatSlow" style={{ animationDelay: "2s" }} />
				<div className="absolute bottom-40 left-1/3 h-64 w-64 rounded-full bg-secondary/8 blur-3xl animate-float" style={{ animationDelay: "4s" }} />
				<div className="absolute -right-10 bottom-20 h-48 w-48 rounded-full bg-accent/8 blur-3xl animate-floatSlow" style={{ animationDelay: "1s" }} />
			</div>

			{/* Hero Section */}
			<section className={`relative flex flex-col items-center pt-16 pb-20 text-center transition-all duration-700 ${mounted ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"}`}>
				<p className="mb-4 text-sm font-semibold uppercase tracking-[0.35em] text-secondary/80">How You Know</p>

				<h1 className="relative text-7xl font-black leading-none tracking-tight sm:text-8xl lg:text-9xl">
					<span
						className="bg-gradient-to-r from-primary via-secondary to-accent bg-[length:200%_auto] bg-clip-text text-transparent animate-gradientShift"
						style={{ animationDuration: "4s" }}
					>
						H.Y.K
					</span>
				</h1>
				<div className="mt-1 h-1 w-24 rounded-full bg-gradient-to-r from-primary to-accent opacity-60" />

				<h2 className="mt-6 text-2xl font-bold text-text sm:text-3xl">
					AI Quiz Battle
				</h2>
				<p className="mt-4 max-w-2xl text-lg leading-relaxed text-text/70">
					Generate playable 10-question quizzes from any lesson, battle in real time,
					and climb the leaderboard with lives, streaks, XP, and achievements.
				</p>

				<div className="mt-10 flex flex-wrap items-center justify-center gap-4">
					<Link
						href="/teacher"
						className="group relative inline-flex items-center gap-2 rounded-2xl bg-gradient-to-r from-primary to-accent px-8 py-4 text-lg font-bold text-bg shadow-glow transition-all duration-300 hover:shadow-glow-lg hover:scale-105"
					>
						<span>🎓</span>
						Create Quiz
						<span className="absolute inset-0 rounded-2xl bg-white/0 transition-all group-hover:bg-white/5" />
					</Link>
					<Link
						href="/join"
						className="group inline-flex items-center gap-2 rounded-2xl border-2 border-primary/60 px-8 py-4 text-lg font-bold text-primary transition-all duration-300 hover:border-primary hover:bg-primary/10 hover:shadow-glow-sm hover:scale-105"
					>
						<span>⚔️</span>
						Join Battle
					</Link>
				</div>
			</section>

			{/* How It Works */}
			<section className={`relative py-16 transition-all duration-700 delay-200 ${mounted ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"}`}>
				<h3 className="mb-12 text-center text-3xl font-bold text-text">
					How It <span className="text-primary">Works</span>
				</h3>
				<div className="grid gap-6 md:grid-cols-3">
					{steps.map((step, i) => (
						<div
							key={step.number}
							className="glass group relative rounded-2xl p-8 transition-all duration-300 hover:-translate-y-2 hover:shadow-glow-sm"
							style={{ animationDelay: `${i * 150}ms` }}
						>
							<div className="absolute -top-4 left-6 flex h-8 w-8 items-center justify-center rounded-full bg-gradient-to-r from-primary to-accent text-sm font-bold text-bg">
								{step.number}
							</div>
							<div className="mb-4 text-4xl">{step.icon}</div>
							<h4 className="mb-2 text-xl font-bold text-text group-hover:text-primary transition-colors">{step.title}</h4>
							<p className="text-sm leading-relaxed text-text/60">{step.description}</p>
						</div>
					))}
				</div>
			</section>

			{/* Features Grid */}
			<section className={`relative py-16 transition-all duration-700 delay-300 ${mounted ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"}`}>
				<h3 className="mb-12 text-center text-3xl font-bold text-text">
					Packed with <span className="text-primary">Features</span>
				</h3>
				<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
					{features.map((feature, i) => (
						<div
							key={feature.title}
							className="glass group rounded-2xl p-6 text-center transition-all duration-300 hover:scale-105 hover:shadow-glow-sm"
							style={{ animationDelay: `${i * 100}ms` }}
						>
							<div className="mb-4 text-4xl transition-transform duration-300 group-hover:scale-110">{feature.icon}</div>
							<h4 className="mb-2 text-lg font-bold text-text">{feature.title}</h4>
							<p className="text-sm text-text/60">{feature.description}</p>
						</div>
					))}
				</div>
			</section>

			{/* Stats Section */}
			<section className={`relative py-16 transition-all duration-700 delay-500 ${mounted ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"}`}>
				<div className="glass rounded-3xl p-10">
					<div className="grid grid-cols-2 gap-8 md:grid-cols-4">
						{stats.map((stat) => (
							<div key={stat.label} className="flex flex-col items-center gap-2">
								<span className="text-3xl">{stat.icon}</span>
								<span className="text-4xl font-black text-primary">{stat.value}</span>
								<span className="text-sm font-medium uppercase tracking-wider text-text/50">{stat.label}</span>
							</div>
						))}
					</div>
				</div>
			</section>
		</div>
	);
}
